package com.techknife.report.entity;

public enum ReportCategoryType {
    SUPPORT,
    HR_REPORTS,
    ATTENDANCE_REPORTS,
    LEAVE_REPORTS,
    PAYROLL_REPORTS,
    RECRUITMENT_REPORTS,
    CRM_REPORTS,
    CUSTOMER_REPORTS,
    PROJECT_REPORTS,
    FINANCE_REPORTS,
    ASSET_REPORTS,
    INVENTORY_REPORTS,
    PROCUREMENT_REPORTS,
    AUDIT_REPORTS,
    SYSTEM_REPORTS
}
