package com.techknife.project.report.service;

import com.techknife.project.analytics.service.ProductivityAnalyticsService;
import com.techknife.project.dashboard.service.ProjectDashboardService;
import com.techknife.project.report.dto.ProjectReportDTO;
import com.techknife.project.resource.service.ResourceAllocationService;
import com.techknife.project.risk.service.ProjectRiskService;
import com.techknife.timetracking.service.TimeTrackingService;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

import java.time.Instant;
import java.time.LocalDate;
import java.util.*;
import java.util.stream.Collectors;

@Slf4j
@Service
@RequiredArgsConstructor
public class ProjectReportService {

    private final ProjectDashboardService projectDashboardService;
    private final ProductivityAnalyticsService productivityAnalyticsService;
    private final ResourceAllocationService resourceAllocationService;
    private final ProjectRiskService projectRiskService;
    private final TimeTrackingService timeTrackingService;

    public ProjectReportDTO generateReport(String reportType, String projectId, String userId) {
        Map<String, Object> metrics = new HashMap<>();
        List<Map<String, Object>> details = new ArrayList<>();

        switch (reportType.toUpperCase()) {
            case "PROJECT_STATUS":
                var dashboard = projectDashboardService.getProjectDashboardSummary(projectId);
                metrics.put("projectName", dashboard.getProjectName());
                metrics.put("health", dashboard.getProjectHealth());
                metrics.put("progressPercentage", dashboard.getProgressPercentage());
                metrics.put("budgetUsed", dashboard.getBudgetUsed());
                metrics.put("totalMilestones", dashboard.getTotalMilestones());
                break;
            case "PRODUCTIVITY":
                var analytics = productivityAnalyticsService.getProductivityAnalytics(projectId);
                metrics.put("totalHoursLogged", analytics.getTotalHoursLogged());
                metrics.put("billableHoursLogged", analytics.getBillableHoursLogged());
                metrics.put("taskCompletionRatePercentage", analytics.getTaskCompletionRatePercentage());
                metrics.put("sprintVelocityAverage", analytics.getSprintVelocityAverage());
                break;
            case "RESOURCE_UTILIZATION":
                var resources = resourceAllocationService.getAllocationsByProject(projectId);
                metrics.put("totalResourcesAllocated", resources.size());
                details = resources.stream().map(r -> {
                    Map<String, Object> map = new HashMap<>();
                    map.put("employeeId", r.getEmployeeId());
                    map.put("utilizationPercentage", r.getUtilizationPercentage());
                    map.put("overAllocated", r.isOverAllocated());
                    return map;
                }).collect(Collectors.toList());
                break;
            case "RISK":
                var risks = projectRiskService.getRisksByProject(projectId);
                metrics.put("totalRisksIdentified", risks.size());
                details = risks.stream().map(r -> {
                    Map<String, Object> map = new HashMap<>();
                    map.put("title", r.getTitle());
                    map.put("impact", r.getImpact());
                    map.put("probability", r.getProbability());
                    map.put("status", r.getStatus());
                    return map;
                }).collect(Collectors.toList());
                break;
            default:
                metrics.put("status", "COMPLETED");
                break;
        }

        return ProjectReportDTO.builder()
                .reportType(reportType)
                .projectId(projectId)
                .generatedAt(Instant.now())
                .generatedBy(userId)
                .summaryMetrics(metrics)
                .reportDetails(details)
                .forecastedCompletionDate(LocalDate.now().plusMonths(3).toString())
                .build();
    }

    public String exportReportToCsv(ProjectReportDTO report) {
        StringBuilder csv = new StringBuilder();
        csv.append("Report Type,Project ID,Generated By,Generated At\n");
        csv.append(String.format("%s,%s,%s,%s\n\n", report.getReportType(), report.getProjectId(), report.getGeneratedBy(), report.getGeneratedAt()));

        csv.append("Summary Metrics\nKey,Value\n");
        if (report.getSummaryMetrics() != null) {
            report.getSummaryMetrics().forEach((k, v) -> csv.append(String.format("%s,%s\n", k, v)));
        }

        return csv.toString();
    }
}
