package com.techknife.analytics.entity;

public enum InsightType {
    TOP_PERFORMING_DEPARTMENT,
    TOP_PERFORMING_EMPLOYEE,
    HIGHEST_REVENUE_CUSTOMER,
    HIGHEST_COST_CENTER,
    LOW_INVENTORY_ALERT,
    HIGH_ATTRITION_ALERT,
    RECRUITMENT_BOTTLENECK,
    PROJECT_DELAY_RISK
}
